[workspace]
resolver = "2"
members = ["cli", "compiler-handwritten", "compiler-peg", "runtime", "shared"]

[workspace.package]
version = "0.1.0"
edition = "2021"
authors = ["Cylix Lee<cylix.lee@outlook.com>"]
