[package]
name = "runtime"
version.workspace = true
edition.workspace = true
authors.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
shared = { path = "../shared" }
codespan-reporting = "0.11.1"
paste = "1.0.14"
